[functions."send-employee-invitation"]
verify_jwt = false

[functions."check-email-availability"]
verify_jwt = false

[functions."delete-auth-user"]
verify_jwt = false

[functions."register-employer"]
verify_jwt = false

[functions."register-employee"]
verify_jwt = false
